import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Sidebar from "./components/sidebar/sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SparkSocket",
  description: "Generated by SparkSocket",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}</body>
    </html>
  );
}
